spring.application.name=tracking-service

spring.cloud.config.profile=dev
server.port=${tracking-service.uriport}
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

eureka.client.service-url.defaultZone: ${tracking-service.urlregistry}

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

